### ISSUE TITLE
DL list view resets on DL complete

### ISSUE THREAD

**Issue by Aki1024** [korslund/Tiggit#2]
Bug: When an install finishes while the user’s view is on the Freeware tab, their category and game selection is reset to first tab first game. (not witnessed if All is already selected)
Expected: Selection remains where the user is currently reading

XP Pro SP3
unknown version of Tiggit (not listed anywhere), dl'ed 4/18/2012

**Comment by korslund** [comment]
Thanks, was caused by an update flag being set when it shouldn't. Fixed.
