### ISSUE TITLE
Seach textbox unexpected keyboard functionality

### ISSUE THREAD

**Issue by Aki1024** [korslund/Tiggit#3]
In the Search textbox, when the delete key is pressed, the focus on the textbox is cleared.  Left and right arrow keys are ignored.  Up and down moves the curser left and right.

Expected: The highlighted text to be removed when delete is pressed, or the next char after the curser removed if no highlighted text.  Left and right arrows to move the curser location, while up and down arrow keys ignored or pushes curser to the front/back of the textbox.

XP Pro SP3, Unknown version of Tiggit (dl'ed 4/18/2012)

**Comment by korslund** [comment]
Thanks for the report. I've identified this as being caused by key accelerator (search tiggit.cpp for wxAcceleratorTable). I haven't determined a plan of action to fix this yet without breaking keyboard shortcuts.

**Comment by korslund** [comment]
Ok, (mostly) fixed. Removed the left/right accelerators which never worked on Windows anyway (worked fine in GTK.) And removed the delete key accelerator from all tabs except the 'Installed' tab, which is the only place where the delete key has any function anyway.

This isn't a complete fix (delete key is still wonky when searching installed games), so I'll leave the issue open.

**Comment by korslund** [comment]
FIXED.

I redid the entire key acceleration method using events instead of wxAcceleratorTable.

Accelerator keys now work on all tabs, and ONLY when the list view has focus (it no longer affects the search box.)

As a bonus, arrow keys (left and right to switch tabs) now also work on Windows.

**Comment by Aki1024** [comment]
Sweet.  Thank you.
