### ISSUE TITLE
"Open Location" of game throws error

### ISSUE THREAD

**Issue by Aki1024** [korslund/Tiggit#4]
In the Installed tab, right clicking a game an selecting "Open Location" opens a command line and throws the error: "Windows cannot find 'K:\Documents'. Make sure you typed the name in correctly then try again."  K is my windows install drive.  See screen: www.leviwatts.com/images/2012.04.20-OpenLocationError.jpg

Windows XP Pro SP3
Unknown version of Tiggit, dl'ed 4/19/2012

**Comment by korslund** [comment]
FIXED: Removed 'Open Location' option from games that are not fully installed.

I can't reproduce this on installed games though - it seems to be working. Was the game in question in the process of downloading / installing?

**Comment by Aki1024** [comment]
I tried this on four games, all of which were already installed.  At a guess, windows is ignoring part of a passed param due to the space in the folder name.

**Comment by korslund** [comment]
Ok, I've changed how explorer is launched (this also removes the unnecessary command line window), and added "" around the dir parameter. Try re-running it now (should auto-update.)

**Comment by Aki1024** [comment]
Like a charm, alpha_34 works for opening the game's location.  Thank you. ^.^
