### ISSUE TITLE
Error parsing all_games.json: cannot read file

### ISSUE THREAD

**Issue by kolen** [korslund/Tiggit#7]
After installing tiggit with installer, right after starting installer, I got message:

> Error parsing 'C:\Users\denred\AppData\Local\tiggit\all_games.json':
> 
> Cannot read file

And then nothing happens (program terminates).
Tiggit icon appears in Start menu, but when I run it again from start menu, I receive the same message.

In AppData\Local\tiggit there is only bin subdirectory with tiggit binaries/dlls, there is no that .json file.

Also, before this message, "Downloading latest update" dialog appears, with progress bar.

Tried to run as regular user and as administrator, the same result.

Maybe problem is that updates cannot be downloaded but it does not show correct message about failed update.

Windows 7 64-bit service pack 1.

**Comment by kolen** [comment]
When it shows message about update, it says that it is downloading:
http://sourceforge.net/projects/tiggit/files/client_data/win32_alpha_039.zip

Tried to open in browser, it redirects to:
http://sourceforge.net/projects/tiggit/files/client_data/win32_alpha_039.zip/download

And it is download page (not direct link to file). Downloaded this zip manually, extracted into `AppData\Local\tiggit\bin` so it replaced `tiggit.exe` and `version`. Ran program again, it said "Downloading data set...", downloaded and now works correctly.

Seems that cause of this problem is that auto-update is not working.

P.S. I used installer downloaded from link on main page of tiggit.net: http://sourceforge.net/projects/tiggit/files/installer/tiggit_setup.exe/download, maybe it is outdated.

**Comment by Jon-Biz** [comment]
This has hit Reddit, fwiw, so you might want to fix it up quick while you still have people's attention.

**Comment by korslund** [comment]
We've just released a new installer http://sourceforge.net/projects/tiggit/files/installer/tiggit_setup.exe/download , it might solve this problem.

(Also the solution outlined in the comments above is now outdated, as alpha_039 is no longer the current version, but it might still work.)

I will close this issue if enough people can confirm that it works. UPDATE: seems it does work, closed.

**Comment by kolen** [comment]
Seems that it is working now. Tried deleting ~/AppData/Local/tiggit, reinstalled again with installer. It installed, downloaded game list and works.

P.S. There is no icon in start menu, but I am not sure, maybe I not checked checkbox to create start menu item, or maybe it is just not supported by intention; I don't created issue for this, if someone will to test this, please test.
